In [1]:
import pandas as pd

df = pd.read_csv("butterfly_dataset_alberta_phase1.csv")

df.head()

,Insect,Scientific name,Stage,Plant,Botanical Name,Role,Relationship,Sun,Growth,Native,Source,Unnamed: 11,Confidence,Source Type
0,Monarch,Danaus plexippus,Host,Low Milkweed,Asclepias ovalifolia,Leaves,Specific,Full,Herbaceous,Yes,https://blog.cwf-fcf.org/index.php/en/monarch-...,NaN,High,Conservation
1,Monarch,Danaus plexippus,Host,Showy Milkweed,Asclepias speciosa,Leaves,Specific,Full,Herbaceous,Yes,https://blog.cwf-fcf.org/index.php/en/monarch-...,NaN,High,Conservation
2,Monarch,Danaus plexippus,Host,Short Green Milkweed,Asclepias viridflora,Leaves,Specific,Full,Herbaceous,Yes,https://blog.cwf-fcf.org/index.php/en/monarch-...,NaN,High,Conservation
3,Monarch,Danaus plexippus,Butterfly,Blazing star,Liatris ligulistylis,Nectar,General,Full,Herbaceous,Yes,https://www.enps.ca/plant-index/meadow-blazing...,NaN,High,Conservation
4,Monarch,Danaus plexippus,Butterfly,Coneflower,Echinacea purpurea,Nectar,General,Full,Herbaceous,No,https://www.birdsandblooms.com/gardening/attra...,NaN,Medium,Horticultural

In [2]:
monarch = df[df["Insect"] == "Monarch"]

monarch

,Insect,Scientific name,Stage,Plant,Botanical Name,Role,Relationship,Sun,Growth,Native,Source,Unnamed: 11,Confidence,Source Type
0,Monarch,Danaus plexippus,Host,Low Milkweed,Asclepias ovalifolia,Leaves,Specific,Full,Herbaceous,Yes,https://blog.cwf-fcf.org/index.php/en/monarch-...,NaN,High,Conservation
1,Monarch,Danaus plexippus,Host,Showy Milkweed,Asclepias speciosa,Leaves,Specific,Full,Herbaceous,Yes,https://blog.cwf-fcf.org/index.php/en/monarch-...,NaN,High,Conservation
2,Monarch,Danaus plexippus,Host,Short Green Milkweed,Asclepias viridflora,Leaves,Specific,Full,Herbaceous,Yes,https://blog.cwf-fcf.org/index.php/en/monarch-...,NaN,High,Conservation
3,Monarch,Danaus plexippus,Butterfly,Blazing star,Liatris ligulistylis,Nectar,General,Full,Herbaceous,Yes,https://www.enps.ca/plant-index/meadow-blazing...,NaN,High,Conservation
4,Monarch,Danaus plexippus,Butterfly,Coneflower,Echinacea purpurea,Nectar,General,Full,Herbaceous,No,https://www.birdsandblooms.com/gardening/attra...,NaN,Medium,Horticultural
5,Monarch,Danaus plexippus,Butterfly,Goldenrod,Solidago,Nectar,General,Full,Herbaceous,Yes,https://www.mun.ca/botanicalgarden/learn/educa...,NaN,High,Educational
6,Monarch,Danaus plexippus,Butterfly,Lilac,Syringa vlugaris,Nectar,General,Full,Shrub,No,https://www.mun.ca/botanicalgarden/learn/educa...,NaN,High,Educational

In [3]:
monarch_host = df[ 
    (df["Insect"] == "Monarch") &
    (df["Role"] == "Host") 
]

monarch_host[["Plant Common", "Plant Scientific"]]

KeyError: "None of [Index(['Plant Common', 'Plant Scientific'], dtype='object')] are in the [columns]"

In [4]:
monarch_host = df[ 
    (df["Insect"] == "Monarch") &
    (df["Stage"] == "Host") 
]

monarch_host[["Plant", "Botanical Name"]]

                  Plant        Botanical Name
0          Low Milkweed  Asclepias ovalifolia
1        Showy Milkweed    Asclepias speciosa
2  Short Green Milkweed  Asclepias viridflora

In [5]:
def get_host_plants(insect_name):
    result = df[
        (df["Insect"] == insect_name) &
        (df["Stage"] == "Host")
    ]
    return result[["Plant", "Botanical Name"]]

In [6]:
get_host_plants("Monarch")

                  Plant        Botanical Name
0          Low Milkweed  Asclepias ovalifolia
1        Showy Milkweed    Asclepias speciosa
2  Short Green Milkweed  Asclepias viridflora

In [7]:
get_host_plants("Meadow Fritillary")

                    Plant    Botanical Name
72  Northern White Violet     Viola pallens
73     Woolly Blue Violet     Viola sororia
74          Canada Violet  Viola canadensis
75         Prairie Violet  Viola pedatifida
76      Early Blue Violet      Viola adunca

In [11]:
get_host_plants("Monarch")
get_host_plants("Meadow Fritillary")

                    Plant    Botanical Name
72  Northern White Violet     Viola pallens
73     Woolly Blue Violet     Viola sororia
74          Canada Violet  Viola canadensis
75         Prairie Violet  Viola pedatifida
76      Early Blue Violet      Viola adunca

In [12]:
user_input = input("Enter a butterfly name: ")

Enter a butterfly name:  Painted Lady

In [14]:
def get_host_plants(insect_name):
    result = df[
        (df["Insect"] == insect_name) &
        (df["Stage"] == "Host")
    ]
    
    if result.empty:
        print("No data found. Check spelling.")
    else:
        return result[["Plant", "Botanical Name"]]

In [15]:
user_input = input("Enter a butterfly name: ")

get_host_plants(user_input)

Enter a butterfly name:  Meadow Fritillary

                    Plant    Botanical Name
72  Northern White Violet     Viola pallens
73     Woolly Blue Violet     Viola sororia
74          Canada Violet  Viola canadensis
75         Prairie Violet  Viola pedatifida
76      Early Blue Violet      Viola adunca

In [16]:
user_input = input("Enter a butterfly name: ")

get_host_plants(user_input)

Enter a butterfly name:  Hosta

No data found. Check spelling.

In [17]:
def get_recommendations(insect_name):
    result = df[df["Insect"] == insect_name]
    
    if result.empty:
        print("No data found. Check spelling.")
        return
    
    host = result[result["Stage"] == "Host"]
    nectar = result[result["Stage"] == "Butterfly"]
    
    print("🐛 Host Plants (for caterpillars):")
    display(host[["Plant", "Botanical Name"]])
    
    print("\n🦋 Nectar Plants (for adult butterflies):")
    display(nectar[["Plant", "Botanical Name"]])

In [18]:
get_recommendations("Monarch")

🐛 Host Plants (for caterpillars):

                  Plant        Botanical Name
0          Low Milkweed  Asclepias ovalifolia
1        Showy Milkweed    Asclepias speciosa
2  Short Green Milkweed  Asclepias viridflora

🦋 Nectar Plants (for adult butterflies):

          Plant        Botanical Name
3  Blazing star  Liatris ligulistylis
4    Coneflower    Echinacea purpurea
5     Goldenrod              Solidago
6         Lilac      Syringa vlugaris

In [19]:
get_recommendations("Red Admiral")

🐛 Host Plants (for caterpillars):

     Plant   Botanical Name
21  Nettle    Urtica dioica
22    Hops  Humulus lupulus

🦋 Nectar Plants (for adult butterflies):

            Plant          Botanical Name
23   Arctic Aster        Eurybia sibirica
24          Aster              Asteraceae
25       Milkweed          Asclepias spp.
26     Red Clover      Trifolium pratense
27        Alfalfa         Medicago sativa
28  Low Goldenrod  Solidago missouriensis
29  Rotting fruit                     NaN

In [20]:
def get_recommendations(insect_name, sun=None, plant_type=None):
    result = df[df["Insect"] == insect_name]
    
    if result.empty:
        print("No data found. Check spelling.")
        return
    
    # Apply filters if provided
    if sun:
        result = result[result["Sun"] == sun]
        
    if plant_type:
        result = result[result["Growth"] == plant_type]
    
    host = result[result["Stage"] == "Host"]
    nectar = result[result["Stage"] == "Butterfly"]
    
    print("🐛 Host Plants (for caterpillars):")
    display(host[["Plant", "Botanical Name"]])
    
    print("\n🦋 Nectar Plants (for adult butterflies):")
    display(nectar[["Plant", "Botanical Name"]])

In [21]:
get_recommendations("Monarch", sun="Full")

🐛 Host Plants (for caterpillars):

                  Plant        Botanical Name
0          Low Milkweed  Asclepias ovalifolia
1        Showy Milkweed    Asclepias speciosa
2  Short Green Milkweed  Asclepias viridflora

🦋 Nectar Plants (for adult butterflies):

          Plant        Botanical Name
3  Blazing star  Liatris ligulistylis
4    Coneflower    Echinacea purpurea
5     Goldenrod              Solidago
6         Lilac      Syringa vlugaris

In [22]:
get_recommendations("Monarch", sun="Full", plant_type="Herbaceous")

🐛 Host Plants (for caterpillars):

                  Plant        Botanical Name
0          Low Milkweed  Asclepias ovalifolia
1        Showy Milkweed    Asclepias speciosa
2  Short Green Milkweed  Asclepias viridflora

🦋 Nectar Plants (for adult butterflies):

          Plant        Botanical Name
3  Blazing star  Liatris ligulistylis
4    Coneflower    Echinacea purpurea
5     Goldenrod              Solidago

In [23]:
def get_supported_butterflies(plant_name, sun=None, plant_type=None):
    result = df[df["Plant"] == plant_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if plant_type:
        result = result[result["Growth"] == plant_type]
    
    if result.empty:
        print("No data found. Check spelling.")
        return
    
    butterflies = result[["Insect", "Stage"]].drop_duplicates().sort_values(by="Insect")
    display(butterflies)

In [24]:
get_supported_butterflies("Birch")

                        Insect Stage
30  Canadian Tiger Swallowtail  Host

In [25]:
get_supported_butterflies("Showy Milkweed")

    Insect Stage
1  Monarch  Host

In [26]:
get_supported_butterflies("Aspen")

                        Insect Stage
31  Canadian Tiger Swallowtail  Host
45              Mourning Cloak  Host

In [27]:
def get_supported_butterflies(plant_name, sun=None, plant_type=None):
    result = df[df["Plant"] == plant_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if plant_type:
        result = result[result["Growth"] == plant_type]
    
    if result.empty:
        print("No data found. Check spelling.")
        return
    
    butterflies = result[["Insect", "Stage", "Sun", "Growth"]].drop_duplicates().sort_values(by="Insect")
    display(butterflies)

In [28]:
get_supported_butterflies("Aspen")

                        Insect Stage   Sun Growth
31  Canadian Tiger Swallowtail  Host  Full   Tree
45              Mourning Cloak  Host  Full   Tree

In [29]:
def get_supported_butterflies(plant_name, sun=None, plant_type=None):
    result = df[df["Plant"] == plant_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if plant_type:
        result = result[result["Growth"] == plant_type]
    
    if result.empty:
        print("No data found. Check spelling.")
        return
    
    # Get unique insect + stage pairs
    butterflies = result[["Insect", "Stage"]].drop_duplicates().sort_values(by="Insect")
    
    print(f"\nButterflies supported by {plant_name}:\n")
    
    for _, row in butterflies.iterrows():
        print(f"- {row['Insect']} — {row['Stage']}")

In [30]:
get_supported_butterflies("Aster")

Butterflies supported by Aster:

- Northern Crescent — Host
- Northern Crescent — Butterfly
- Painted Lady — Butterfly
- Red Admiral — Butterfly

In [31]:
def get_supported_butterflies(plant_name, sun=None, plant_type=None):
    result = df[df["Plant"] == plant_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if plant_type:
        result = result[result["Growth"] == plant_type]
    
    if result.empty:
        print("No data found. Check spelling.")
        return
    
    print(f"\nButterflies supported by {plant_name}:\n")
    
    # Group by insect
    grouped = result.groupby("Insect")["Stage"].unique()
    
    for insect, stages in grouped.items():
        stage_list = " + ".join(stages)
        print(f"- {insect} — {stage_list}")

In [32]:
get_supported_butterflies(Aster)

NameError: name 'Aster' is not defined

In [33]:
get_supported_butterflies("Aster")

Butterflies supported by Aster:

- Northern Crescent — Host + Butterfly
- Painted Lady — Butterfly
- Red Admiral — Butterfly

In [34]:
def get_garden_plan(insect_name, sun=None):
    result = df[df["Insect"] == insect_name]
    
    if sun:
        result = result[result["Sun"] == sun]
    
    if result.empty:
        print("No data found. Check spelling.")
        return
    
    host = result[result["Stage"] == "Host"]
    nectar = result[result["Stage"] == "Butterfly"]
    
    print(f"\n🌱 Garden plan for {insect_name}:\n")
    
    print("🐛 Host plants (must-have):")
    for plant in host["Plant"].unique():
        print(f"- {plant}")
    
    print("\n🦋 Nectar plants (support adults):")
    for plant in nectar["Plant"].unique():
        print(f"- {plant}")

In [35]:
get_garden_plan("Meadow Fritillary")

🌱 Garden plan for Meadow Fritillary:

🐛 Host plants (must-have):
- Northern White Violet
- Woolly Blue Violet
- Canada Violet
- Prairie Violet
- Early Blue Violet

🦋 Nectar plants (support adults):
- Black-eyed Susan
- Yarrow
- Echinacea
- Alpine Aster

In [36]:
def get_garden_plan(insect_name, sun=None):
    result = df[df["Insect"] == insect_name]
    
    if sun:
        result = result[result["Sun"] == sun]
    
    if result.empty:
        print("No data found. Check spelling or filter choice.")
        return
    
    host = result[result["Stage"] == "Host"]
    nectar = result[result["Stage"] == "Butterfly"]
    
    print(f"\n🌱 Garden plan for {insect_name}")
    
    if sun:
        print(f"☀️ Sun requirement filter: {sun}")
    
    print("\n🐛 Host plants (must-have):")
    for plant in host["Plant"].unique():
        print(f"- {plant}")
    
    print("\n🦋 Nectar plants (support adults):")
    for plant in nectar["Plant"].unique():
        print(f"- {plant}")

In [37]:
get_garden_plan("Meadow Fritillary", sun="Full")

🌱 Garden plan for Meadow Fritillary
☀️ Sun requirement filter: Full

🐛 Host plants (must-have):
- Prairie Violet

🦋 Nectar plants (support adults):
- Black-eyed Susan
- Yarrow
- Echinacea
- Alpine Aster

In [38]:
def get_garden_plan(insect_name, sun=None, growth=None):
    result = df[df["Insect"] == insect_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if growth:
        result = result[result["Growth"] == growth]
    
    if result.empty:
        print("No data found. Check spelling or filter choice.")
        return
    
    host = result[result["Stage"] == "Host"]
    nectar = result[result["Stage"] == "Butterfly"]
    
    print(f"\n🌱 Garden plan for {insect_name}")
    
    if sun:
        print(f"☀️ Sun requirement filter: {sun}")
    if growth:
        print(f"🌿 Growth filter: {growth}")
    
    print("\n🐛 Host plants (must-have):")
    for plant in host["Plant"].unique():
        print(f"- {plant}")
    
    print("\n🦋 Nectar plants (support adults):")
    for plant in nectar["Plant"].unique():
        print(f"- {plant}")

In [39]:
get_garden_plan("Red Admiral", sun="Full", growth="Herbaceous")

🌱 Garden plan for Red Admiral
☀️ Sun requirement filter: Full
🌿 Growth filter: Herbaceous

🐛 Host plants (must-have):

🦋 Nectar plants (support adults):
- Arctic Aster
- Aster
- Milkweed
- Red Clover
- Alfalfa
- Low Goldenrod

In [41]:
def get_garden_plan(insect_name, sun=None, growth=None):
    result = df[df["Insect"] == insect_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if growth:
        result = result[result["Growth"] == growth]
    
    if result.empty:
        print("No data found. Check spelling or filter choice.")
        return
    
    host = result[result["Stage"] == "Host"]
    nectar = result[result["Stage"] == "Butterfly"]
    
    print(f"\n🌱 Garden plan for {insect_name}")
    
    if sun:
        print(f"☀️ Sun requirement filter: {sun}")
    if growth:
        print(f"🌿 Growth filter: {growth}")
    
    print("\n🐛 Host plants (must-have):")
    for _, row in host[["Plant", "Botanical Name"]].drop_duplicates().iterrows():
        print(f"- {row['Plant']} ({row['Botanical Name']})")
    
    print("\n🦋 Nectar plants (support adults):")
    for _, row in nectar[["Plant", "Botanical Name"]].drop_duplicates().iterrows():
        print(f"- {row['Plant']} ({row['Botanical Name']})")

In [42]:
get_garden_plan("Monarch", sun="Full", growth="Herbaceous")

🌱 Garden plan for Monarch
☀️ Sun requirement filter: Full
🌿 Growth filter: Herbaceous

🐛 Host plants (must-have):
- Low Milkweed (Asclepias ovalifolia)
- Showy Milkweed (Asclepias speciosa)
- Short Green Milkweed (Asclepias viridflora)

🦋 Nectar plants (support adults):
- Blazing star (Liatris ligulistylis)
- Coneflower (Echinacea purpurea)
- Goldenrod (Solidago)

In [43]:
def get_garden_plan(insect_name, sun=None, growth=None):
    result = df[df["Insect"] == insect_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if growth:
        result = result[result["Growth"] == growth]
    
    if result.empty:
        print("No data found. Check spelling or filter choice.")
        return
    
    host = result[result["Stage"] == "Host"][["Plant", "Botanical Name"]].drop_duplicates()
    nectar = result[result["Stage"] == "Butterfly"][["Plant", "Botanical Name"]].drop_duplicates()
    
    print(f"\n🌱 Garden plan for {insect_name}")
    
    if sun:
        print(f"☀️ Sun requirement filter: {sun}")
    if growth:
        print(f"🌿 Growth filter: {growth}")
    
    print("\n🐛 Host plants (must-have):")
    for _, row in host.iterrows():
        print(f"- {row['Plant']} ({row['Botanical Name']})")
    
    print("\n🦋 Nectar plants (support adults):")
    for _, row in nectar.iterrows():
        print(f"- {row['Plant']} ({row['Botanical Name']})")
    
    print("\n✨ Suggested starter planting mix:")
    
    host_mix = host.head(2)
    nectar_mix = nectar.head(3)
    
    print("Start with:")
    for _, row in host_mix.iterrows():
        print(f"- 1 host plant: {row['Plant']} ({row['Botanical Name']})")
    
    for _, row in nectar_mix.iterrows():
        print(f"- 1 nectar plant: {row['Plant']} ({row['Botanical Name']})")

In [44]:
get_garden_plan("Painted Lady", sun="Full", growth="Herbaceous")

🌱 Garden plan for Painted Lady
☀️ Sun requirement filter: Full
🌿 Growth filter: Herbaceous

🐛 Host plants (must-have):
- Hooker's Thistle (Cirsium hookerianum)
- Sunflower (Helianthus spp.)
- Hollyhock (Alcea)
- Borage (Borago officinalis)

🦋 Nectar plants (support adults):
- Blazing star (Liatris ligulistylis)
- Zinnia (Zinnia elegans)
- Cosmos (Cosmos spp)
- Aster (Asteraceae)

✨ Suggested starter planting mix:
Start with:
- 1 host plant: Hooker's Thistle (Cirsium hookerianum)
- 1 host plant: Sunflower (Helianthus spp.)
- 1 nectar plant: Blazing star (Liatris ligulistylis)
- 1 nectar plant: Zinnia (Zinnia elegans)
- 1 nectar plant: Cosmos (Cosmos spp)

In [45]:
def get_garden_plan(insect_name, sun=None, growth=None, mode="starter"):
    result = df[df["Insect"] == insect_name]
    
    if sun:
        result = result[result["Sun"] == sun]
        
    if growth:
        result = result[result["Growth"] == growth]
    
    if result.empty:
        print("No data found. Check spelling or filter choice.")
        return
    
    host = result[result["Stage"] == "Host"][["Plant", "Botanical Name"]].drop_duplicates()
    nectar = result[result["Stage"] == "Butterfly"][["Plant", "Botanical Name"]].drop_duplicates()
    
    print(f"\n🌱 Garden plan for {insect_name}")
    
    if sun:
        print(f"☀️ Sun requirement filter: {sun}")
    if growth:
        print(f"🌿 Growth filter: {growth}")
    
    if mode == "full":
        print("\n🐛 Host plants (must-have):")
        for _, row in host.iterrows():
            print(f"- {row['Plant']} ({row['Botanical Name']})")
        
        print("\n🦋 Nectar plants (support adults):")
        for _, row in nectar.iterrows():
            print(f"- {row['Plant']} ({row['Botanical Name']})")
    
    elif mode == "starter":
        print("\n✨ Suggested starter planting mix:")
        
        host_mix = host.head(2)
        nectar_mix = nectar.head(3)
        
        print("Start with:")
        for _, row in host_mix.iterrows():
            print(f"- 1 host plant: {row['Plant']} ({row['Botanical Name']})")
        
        for _, row in nectar_mix.iterrows():
            print(f"- 1 nectar plant: {row['Plant']} ({row['Botanical Name']})")
    
    else:
        print("Mode not recognized. Use 'full' or 'starter'.")

In [46]:
get_garden_plan("Monarch", sun="Full", growth="Herbaceous", mode="starter")

🌱 Garden plan for Monarch
☀️ Sun requirement filter: Full
🌿 Growth filter: Herbaceous

✨ Suggested starter planting mix:
Start with:
- 1 host plant: Low Milkweed (Asclepias ovalifolia)
- 1 host plant: Showy Milkweed (Asclepias speciosa)
- 1 nectar plant: Blazing star (Liatris ligulistylis)
- 1 nectar plant: Coneflower (Echinacea purpurea)
- 1 nectar plant: Goldenrod (Solidago)

In [47]:
get_garden_plan("Meadow Fritillary", sun="Full", growth="Herbaceous", mode="full")

🌱 Garden plan for Meadow Fritillary
☀️ Sun requirement filter: Full
🌿 Growth filter: Herbaceous

🐛 Host plants (must-have):
- Prairie Violet (Viola pedatifida)

🦋 Nectar plants (support adults):
- Black-eyed Susan (Rudbeckia hirta)
- Yarrow (Achillea millefolium)
- Echinacea (Echinacea purpurea)
- Alpine Aster (Aster alpinus)